stages:
  - build
  - test

before_script:
  - chmod +x mvnw

build_job:
  stage: build
  script: mvn package
  artifacts:
    paths:
      - target/petclinic.war
  image: maven:3.3.9-jdk-8
  
test_job:
  stage: test
  script: mvn test
  artifacts:
    paths:
      - target/petclinic.war
  image: maven:3.3.9-jdk-8